### ISSUE TITLE
[BUG] Add error/help message if no arguments are given on roll commands

### ISSUE THREAD

**Issue by AlifAlfa73** [ppukj-dev/rice-doll#12]
As title said

**Comment by IqrarAminullah** [comment]
Fix with https://github.com/ppukj-dev/rice-doll/commit/f2430850110967ece04f3a688086e179970764be  https://github.com/ppukj-dev/rice-doll/commit/ed667a2f59542b36f0156ba7459b718950eaa0e9 https://github.com/ppukj-dev/rice-doll/commit/afdd2740b57d812b936c47a188d9b816a0861e95
