### ISSUE TITLE
[IMPROVEMENT] Making Sidekick-Style boolean roller

### ISSUE THREAD

**Issue by IqrarAminullah** [ppukj-dev/rice-doll#17]
Currently, The Avrae boolean roller sums the result of the diceroll then compare the result with a boolean expression
- Example :
Expression : 3d6>3
Roll Result : 4,1,6
Final Result : 1, or True (since 4+1+6 = 11, and 11 is larger than 3)

The Objective is to make Sidekick Bot-Style Boolean Roller, which compares each dice roll result with a boolean expression
- Example 1:
Expression : 3d6>3
Roll Result : 4,1,6
Final Result : 2 (Since 4 and 6 are both larger than 3, but 1 is not)

- Example 2: (Closed group image)
[Discord Image](https://media.discordapp.net/attachments/731079354985087006/746405368888033380/unknown.png)

**Comment by IqrarAminullah** [comment]
https://github.com/ppukj-dev/rice-doll/commit/46544b850c25f83dd69fe397ac5dfe41d6c2d6d1
https://github.com/ppukj-dev/rice-doll/commit/1f28146758f6f17562d5390a2f6a92f45e374214

**Comment by AlifAlfa73** [comment]
Homework
Fix wrong parsing for boolean of "=" expression
Ex: `/r 3d6=4`

**Comment by IqrarAminullah** [comment]
fixed
https://github.com/ppukj-dev/rice-doll/commit/be7299e3b57e1d79226acc30ae96c4b473775a19
