### ISSUE TITLE
Ghostbuster Dice

### ISSUE THREAD

**Issue by IqrarAminullah** [ppukj-dev/rice-doll#4]
Making a dice parser for ghostbuster system

**Comment by AlifAlfa73** [comment]
Added MVP for ghost roll
Example:
![image](https://user-images.githubusercontent.com/23472766/142969060-a1897d1a-d66f-4d71-9832-0598ea067210.png)

Todo:
- Highlight the ghost_die by using strikethrough or bold. Idea: utilize stringify of d20
